### ISSUE TITLE
help

### ISSUE THREAD

**Issue by skiely** [habitual69/thetvappstream#1]
Fixed

**Comment by skiely** [comment]
right, i've cloned the git with gitbash, same error "could not find module server.js" i dont understand what or where i should do with "cd StreamFlowTV" i didnt use that anywhere in setup????
any help much appreciated :)

**Comment by skiely** [comment]
disregard "cd StreamFlowTV" problem..

**Comment by habitual69** [comment]
My bad I made some changes to the code structure but did not update the Readme 😂
